### PR TITLE
Update hyperparameters of bb methods

### PR DESCRIPTION
**Pull request by negvet**
For the reference maps, see https://github.com/openvinotoolkit/openvino_xai/pull/63

Future work: measure metrics

### CODE REVIEW

**Review by goodsong81 — DISMISSED** [review]

**Comment by GalyaZalesskaya** [comment]
Did you update presets using metrics or manually checking quality of the saliency maps in #63?

Also, the table of contents for some reason doesn't show the inner structure of `XAI overview methods`. Can you check what went wrong there, please? 
image

**Comment by negvet** [comment]
> Did you update presets using metrics or manually checking quality of the saliency maps in https://github.com/openvinotoolkit/openvino_xai/pull/63?

I have not used metrics, just qualitative assessment for now. Quantitative analysis is in TODO list

**Comment by negvet** [comment]
> Also, the table of contents for some reason doesn't show the inner structure of XAI overview methods. Can you check what went wrong there, please?

This is intentional. Do you think we need it? Probably it will be too long, what do you think? May be the main subsections only..

**Comment by GalyaZalesskaya** [comment]
> > Also, the table of contents for some reason doesn't show the inner structure of XAI overview methods. Can you check what went wrong there, please?
> 
> This is intentional. Do you think we need it? Probably it will be too long, what do you think? May be the main subsections only..

Let's make it for inly main subsections: white-box and black box

**Review by GalyaZalesskaya — APPROVED** [review]

**Comment by negvet** [comment]
> Let's make it for inly main subsections: white-box and black box

Done

**Pull request merged**
